mkdir datasets
mkdir datasets/test
mkdir datasets/test/input
mkdir datasets/test/target
mkdir datasets/train
mkdir datasets/train/input
mkdir datasets/train/target
mkdir results
mkdir results/gt
mkdir results/output
